name: dart_board_backend
description: Dartboard backend service
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  args: ^1.6.0
  shelf: ^0.7.9

dev_dependencies:
  pedantic: ^1.9.2
